diplom/urls.py
from django.contrib import admin
from django.urls import path, include
from satellite_production import urls as prod_urls
from diplom_base import urls as base_urls
from django.views.generic.base import RedirectView

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'images/', include('images.urls')),
    path(r'production/', include('satellite_production.urls')),
    # Стандартные виды для главной страницы и др.
    path(r'', include('diplom_base.urls')),
    # Стандартное перенаправление
    path(r'.+', RedirectView.as_view(url="/")),
]

diplom_base/urls.py
from .views import *
from django.urls import path

app_name = 'diplom_base'
urlpatterns = [
    path(r'about', AboutView.as_view(), name='about'),
    path(r'', HomePageView.as_view(), name='home'),
]

images/urls.py
from .views import *
from django.urls import path

app_name = 'images'
urlpatterns = [
    path(r'', ImageView.as_view(), name='image_view'),
]

satellite_production/urls.py
from .views import *
from django.urls import path

app_name = 'satellite_production'
urlpatterns = [
    path(r'tables', MultitableView.as_view(), name='multiple_tables_view'),
]

templates/header.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">
</head>
<body>
<header class="navbar navbar-expand-md navbar-light bg-light sticky-top align-self-start">
    <a class="navbar-brand" href="/">Электро-Л №3</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-header-content" aria-controls="navbar-header-content" aria-expanded="false" aria-label="Скрыть / раскрыть меню">
        <span class="navbar-toggler-icon"></span>
    </button>
    {# Автоматическое переключение индикатора данной страницы #}
    {# Также можно использовать resolver_match.app_name и т.д., но русские имена тогда нужно хранить ещё где-то #}
    {% with request.resolver_match.url_name as curr_page %}
    <div id="navbar-header-content">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item{% ifequal curr_page 'home' %} active{% endifequal %}">
                <a href="{% url 'diplom_base:home' %}" class="nav-link">Главная</a>
            </li>
            <li class="nav-item{% ifequal curr_page 'image_view' %} active{% endifequal %}">
                <a href="{% url 'images:image_view' %}" class="nav-link">Архив снимков</a>
            </li>
            <li class="nav-item{% ifequal curr_page 'multiple_tables_view' %} active{% endifequal %} %}">
                <a href="{%  url 'satellite_production:multiple_tables_view' %}" class="nav-link">Таблица выполняемых операций</a>
            </li>
            <li class="nav-item{% ifequal curr_page 'about' %} active{% endifequal %}">
                <a href="{% url 'diplom_base:about' %}" class="nav-link">О сайте</a>
            </li>
        </ul>
    </div>
    {% endwith %}
</header>

    {% block content %}
    {% endblock %}
<footer>


</footer>
</body>
    <script src="{% static 'scripts/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'scripts/bootstrap.min.js' %}"></script>
    {% block page_scripts %}
    {% endblock %}
</html>